name: autofix.ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  autofix:
    uses: bjmhe/workflows/.github/workflows/autofix.yml@vp
    permissions:
      contents: read
    with:
      command: vp check --fix && vp run build --update-snapshot
