name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  unit-test:
    uses: bjmhe/workflows/.github/workflows/unit-test.yml@vp

  coverage:
    uses: bjmhe/workflows/.github/workflows/coverage.yml@vp
    needs: unit-test
    permissions:
      id-token: write
